[Appearance]
window_width = 280
window_height = 200
font_size = 11

[Paths]
downloads_path = C:\Users\yokam\Downloads
output_path = C:\Shinseikai\audiofilesplit\output

[Audio]
target_size_mb = 20
output_file_format = m4a

[LOGGING]
log_retention_days = 7
log_directory = logs
# DEBUG,INFO,WARNING,ERROR
log_level = INFO
debug_mode = True
project_name = audiofilesplit